### ISSUE TITLE
Anaconda 3 in setup.sh

### ISSUE THREAD

**Issue by zingbretsenb** [datasci-w266/2018-spring-main#1]
The setup.sh script in a0 downloads anaconda 3:
`ANACONDA_INSTALLER="Anaconda3-5.0.1-Linux-x86_64.sh"`

but the rest of the script references anaconda 2:
`${HOME}/anaconda2/bin/pip install --upgrade pip`

Also, ao.ipynb uses the Python 2 style of print statement instead of the Python 3 style.
`print "%s version %s is" % (libname, m.__version__),`

Should the setup script be installing anaconda 2 instead?

**Comment by jameskunz** [comment]
You are ahead of us ;)

We'll announce the availability of everything in ISVC!  Don't waste your time until we do.
